# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.define "gw" do |gw|
    gw.vm.hostname = "gateway"
    gw.vm.provider "virtualbox" do |vb|
      vb.name = "gateway"
      vb.cpus = 2
      vb.memory = 2048
    end
    gw.vm.network "public_network" #DHCP
    gw.vm.network "private_network", ip: "192.168.123.254", virtualbox__intnet: true

    gw.vm.provision "shell", inline: <<-SCRIPT
      # Add provisioning script for gateway here
    SCRIPT
  end

  config.vm.define "nginx" do |nginx|
    nginx.vm.hostname = "nginx-server"
    nginx.vm.provider "virtualbox" do |vb|
      vb.name = "nginx-server"
      vb.cpus = 2
      vb.memory = 2048
    end
    nginx.vm.network "private_network", ip: "192.168.223.10", virtualbox__intnet: true
   
    nginx.vm.provision "shell", inline: <<-SCRIPT
      # Add provisioning script for nginx-server here
    SCRIPT
  end

  config.vm.define "web-serve1" do |web_server1|
    web_server1.vm.hostname = "web-server1"
    web_server1.vm.provider "virtualbox" do |vb|
      vb.name = "web-server1"
      vb.cpus = 2
      vb.memory = 2048
    end
    web_server1.vm.network "private_network", ip: "192.168.223.20", virtualbox__intnet: true

    web_server1.vm.provision "shell", inline: <<-SCRIPT
      # Add provisioning script for web-server1 here
    SCRIPT
  end

  config.vm.define "nginx_lb" do |nginx_lb|
    nginx_lb.vm.hostname = "nginx-lb"
    nginx_lb.vm.provider "virtualbox" do |vb|
    vb.name = "nginx-lb"
    vb.cpus = 2
    vb.memory = 2048
    end
    #ubuntu 20.04의 인터페이스명-> enp0s8
    nginx_lb.vm.network "private_network", ip: "192.168.123.10", virtualbox__intnet: true
    #ubuntu 20.04의 인터페이스명-> enp0s9
    nginx_lb.vm.network "private_network", ip: "192.168.223.1", virtualbox__intnet: true
    nginx_lb.vm.provision "shell", inline: <<-SCRIPT
      # Add provisioning script for web-server2 here
    SCRIPT
  end
end
